---
- name: create virtual host file
  template: src=templates/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.com.conf
- name: a2ensite {{ domain }}.com
  command: a2ensite {{ domain }}.com
  notify:
      - restart apache
